/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacymanage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;

import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kriti
 */
 public class available extends javax.swing.JFrame {

    /**
     * Creates new form available
     */
    public available() {
        initComponents();
        table_update();
    }
    
    Connection con1;
PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txttable = new javax.swing.JTable();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttype = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtmdate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtedate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcost = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(36, 47, 65));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(null);

        txttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "medicine id", "medicine name", "medicine type", "manufacturing date", "expiry date", "cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        txttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txttable);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(91, 128, 720, 402);

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel2.add(btnedit);
        btnedit.setBounds(620, 550, 59, 29);

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btndelete);
        btndelete.setBounds(730, 550, 77, 29);

        jButton1.setText("<---");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(750, 20, 63, 29);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanage/icons8-hospital-96.png"))); // NOI18N
        jLabel8.setText("ROFFE PHARMA");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(100, 10, 220, 90);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1010, 780));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, -1, -1));

        jPanel3.setBackground(new java.awt.Color(97, 212, 195));
        jPanel3.setLayout(null);

        jLabel7.setText("Add new medicine");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(84, 20, 131, 20);

        jLabel1.setText("medicine name");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(15, 82, 107, 20);

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel3.add(txtname);
        txtname.setBounds(15, 111, 110, 26);

        jLabel2.setText("medicine type ");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(15, 193, 103, 20);

        txttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tablet", "drops", "syrup", "ointment", "spray" }));
        txttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttypeActionPerformed(evt);
            }
        });
        jPanel3.add(txttype);
        txttype.setBounds(15, 231, 94, 26);

        jLabel4.setText("manufacturing date");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(15, 315, 137, 20);
        jPanel3.add(txtmdate);
        txtmdate.setBounds(15, 353, 140, 26);

        jLabel3.setText("expiry date");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(15, 419, 78, 20);
        jPanel3.add(txtedate);
        txtedate.setBounds(15, 448, 130, 26);

        jLabel6.setText("Cost");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(15, 519, 31, 20);
        jPanel3.add(txtcost);
        txtcost.setBounds(15, 548, 140, 26);

        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel3.add(btnadd);
        btnadd.setBounds(180, 590, 100, 40);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void table_update()
{
        try {
            int c;
            
            
            try {
                Class.forName("com.mysql.jdbc.Driver");
                 con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy", "root", "");
            pst= con1.prepareStatement("select * from stocks");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsd = rs.getMetaData();
            c= rsd.getColumnCount();
            DefaultTableModel d= (DefaultTableModel)txttable.getModel();
            d.setRowCount(0);
            while(rs.next())
            {
                Vector v2= new Vector();
                for (int i=1; i<=c; i++)
                {
                    
                    v2.add(rs.getString("stkmdcn_id"));
                    
                    v2.add(rs.getString("stkmdcn_name"));
                   
                    v2.add(rs.getString("stkmdcn_type"));
                    v2.add(rs.getString("stkmanufg_date"));
                    v2.add(rs.getString("stkexpiry_date"));
                    v2.add(rs.getString("stkmdcn_cost"));
                }
            d.addRow(v2);
            
            }
            
            
            
            
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(available.class.getName()).log(Level.SEVERE, null, ex);
            }
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy", "root", "");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(available.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
}
    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
String name= txtname.getText();

String type=txttype.getSelectedItem().toString();
String mdate= txtmdate.getText(); 
String edate= txtedate.getText(); 
String cost= txtcost.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy", "root", "");
       pst= con1.prepareStatement("insert into stocks(stkmdcn_name,stkmdcn_type,stkmanufg_date, stkexpiry_date, stkmdcn_cost)values (?,?,?,?,?)");
       
          pst.setString(1,name );
            pst.setString(2, type);
              pst.setString(3, mdate);
            pst.setString(4, edate);
             pst.setString(5, cost);
            
    pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully added!!");
            table_update();
            txtname.setText("");
            txttype.setSelectedIndex(-1);
             txtmdate.setText("");
              txtedate.setText("");
              txtcost .setText("");
             
        txtname.requestFocus();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(available.class.getName()).log(Level.SEVERE, null, ex);
      
            
        } catch (SQLException ex) {
            Logger.getLogger(available.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }                                      
//GEN-LAST:event_btnaddActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {                                        
                                              
       DefaultTableModel d1= (DefaultTableModel)txttable.getModel();
            int selectIndex = txttable.getSelectedRow();
            int id = Integer.parseInt(d1.getValueAt(selectIndex,0).toString());
            String name= txtname.getText(); 
            
String type=txttype.getSelectedItem().toString();
String mdate= txtmdate.getText(); 
String edate= txtedate.getText(); 
String cost= txtcost.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy", "root", "");
       pst= con1.prepareStatement("update stocks set stkmdcn_name=?, stkmdcn_type=?,stkmanufg_date=?, stkexpiry_date=?, stkmdcn_cost=? where stkmdcn_id= ?");
       
          pst.setString(1,name );
            pst.setString(2, type);
              pst.setString(3, mdate);
            pst.setString(4, edate);
             pst.setString(5, cost);
             pst.setInt(6, id);
             
    pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Stock Successfully Updated!!");
            table_update();
            txtname.setText("");
           
            txttype.setSelectedIndex(-1);
             txtmdate.setText("");
              txtedate.setText("");
              txtcost .setText("");
        txtname.requestFocus();

            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(available.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(available.class.getName()).log(Level.SEVERE, null, ex);
        }
            


    }                                       

    private void txttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttableMouseClicked
        DefaultTableModel d1= (DefaultTableModel)txttable.getModel();
            int selectIndex = txttable.getSelectedRow();
           txtname.setText(d1.getValueAt(selectIndex,1).toString());
          
            txttype.setSelectedItem(d1.getValueAt(selectIndex,2).toString());
             txtmdate.setText(d1.getValueAt(selectIndex,3).toString()); 
              txtedate.setText(d1.getValueAt(selectIndex,4).toString());
               txtcost.setText(d1.getValueAt(selectIndex,5).toString());
             
            
            
    }//GEN-LAST:event_txttableMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
          DefaultTableModel d1= (DefaultTableModel)txttable.getModel();
            int selectIndex = txttable.getSelectedRow();
            int id = Integer.parseInt(d1.getValueAt(selectIndex,0).toString());
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the Record?", "Warning", JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION)
            {
              try {
                  Class.forName("com.mysql.jdbc.Driver");
                  con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy", "root", "");
                  pst= con1.prepareStatement("delete from stocks where stkmdcn_id=?");   
                  pst.setInt(1,id );
                  pst.executeUpdate();
                  JOptionPane.showMessageDialog(null, "Stock Successfully Deleted!!");
                  table_update();
                  txtname.setText("");
                   
                  txttype.setSelectedIndex(-1);
                  txtmdate.setText("");
                  txtedate.setText("");
                  txtcost .setText("");
                  txtname.requestFocus();
               } catch (ClassNotFoundException ex) {
                  Logger.getLogger(available.class.getName()).log(Level.SEVERE, null, ex);
               } catch (SQLException ex) {
                  Logger.getLogger(available.class.getName()).log(Level.SEVERE, null, ex);
               }
            
            
            
            }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new available().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtcost;
    private javax.swing.JTextField txtedate;
    private javax.swing.JTextField txtmdate;
    private javax.swing.JTextField txtname;
    private javax.swing.JTable txttable;
    private javax.swing.JComboBox<String> txttype;
    // End of variables declaration//GEN-END:variables
}
