/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacymanage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kriti
 */
public class second extends javax.swing.JFrame {

    /**
     * Creates new form second
     */
    public second() {
        initComponents();
        Fillcombo();
    }
    PreparedStatement pst;
   
    Connection con1;
    
    public  void Fillcombo()
{
 try{
     Class.forName("com.mysql.jdbc.Driver");
 
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");
            Statement stmt=con.createStatement();
            String query = "SELECT * from stocks";
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next()){
                mdcnname.addItem(rs.getString("stkmdcn_name"));
            }
    
}
    catch(Exception e){   
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        custdob = new javax.swing.JTextField();
        custreceipt = new javax.swing.JTextField();
        custphone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        custname = new javax.swing.JTextField();
        custdoctor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        mdcncost = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mdcntype = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        mdcnquantity = new javax.swing.JTextField();
        mdcnname = new javax.swing.JComboBox<>();
        btnsubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, null, java.awt.Color.darkGray));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(97, 212, 195));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CUTOMER DETAILS", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(custdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 190, -1));
        jPanel3.add(custreceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 190, -1));

        custphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custphoneActionPerformed(evt);
            }
        });
        jPanel3.add(custphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 190, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("cust_phone");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));
        jPanel3.add(custname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 190, -1));
        jPanel3.add(custdoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 190, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("cust_name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 130, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("dob");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("doctor_id");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("receipt_date");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 440, 300));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanage/icons8-hospital-96.png"))); // NOI18N
        jLabel7.setText("ROFFE PHARMA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 130));

        jButton3.setText("<--");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 60, 20));

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MEDICIN DETAILS", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("reset");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, -1, -1));
        jPanel2.add(mdcncost, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 190, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("mdcn_type");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("mdcn_cost");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("mdcn_name");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        mdcntype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablet", "drops", "syrup", "ointment", "spray" }));
        mdcntype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdcntypeActionPerformed(evt);
            }
        });
        jPanel2.add(mdcntype, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("quantity");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        mdcnquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdcnquantityActionPerformed(evt);
            }
        });
        jPanel2.add(mdcnquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 190, -1));

        mdcnname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mdcnnameItemStateChanged(evt);
            }
        });
        mdcnname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdcnnameActionPerformed(evt);
            }
        });
        jPanel2.add(mdcnname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 190, -1));

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 440, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 811, 726));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mdcnquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdcnquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mdcnquantityActionPerformed

    private void mdcnnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdcnnameActionPerformed

    }//GEN-LAST:event_mdcnnameActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        String cname = custname.getText();
            String dob = custdob.getText();
            String doctor = custdoctor.getText();
            String receipt = custreceipt.getText();
            String phone = custphone.getText();  
            String name = mdcnname.getSelectedItem().toString();
            String cost = mdcncost.getText();
            String type = mdcntype.getSelectedItem().toString();
            String quantity = mdcnquantity.getText();
            
try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy", "root", "");
             pst = con1.prepareStatement("insert into customer(cust_name, dob, doctor_id, receipt_date,cust_phone, mdcn_name, mdcn_cost, mdcn_type, quantity) values(?,?,?,?,?,?,?,?,?)" );
            pst.setString(1, cname);
            pst.setString(2, dob);
            pst.setString(3, doctor);
            pst.setString(4, receipt);
            pst.setString(5, phone);
            pst.setString(6, name);
            pst.setString(7, cost);
            pst.setString(8, type);
            pst.setString(9, quantity);
            
           
            pst.executeUpdate();
              JOptionPane.showMessageDialog(null, "inserted succesfully");
            custname.setText("");
            custdoctor.setText("");
            custreceipt.setText("");
            custphone.setText("");
            mdcncost.setText("");
            mdcnquantity.setText("");
            custdob.setText("");     
            mdcnname.setSelectedIndex(0);
            mdcntype.setSelectedIndex(0);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(second.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(second.class.getName()).log(Level.SEVERE, null, ex);
        }
           



            
                   // TODO add your handling code here:
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void custphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custphoneActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mdcnnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mdcnnameItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_mdcnnameItemStateChanged

    private void mdcntypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdcntypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mdcntypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new second().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.JTextField custdob;
    private javax.swing.JTextField custdoctor;
    private javax.swing.JTextField custname;
    private javax.swing.JTextField custphone;
    private javax.swing.JTextField custreceipt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField mdcncost;
    private javax.swing.JComboBox<String> mdcnname;
    private javax.swing.JTextField mdcnquantity;
    private javax.swing.JComboBox<String> mdcntype;
    // End of variables declaration//GEN-END:variables

}
