/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacymanage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kriti
 */
public class Statistics extends javax.swing.JFrame {

    /**
     * Creates new form Statistics
     */
    public Statistics() {
        initComponents();
        maxCost();
        minCost();
        maxbought();
        minbought();
        exp();
        tq();
        ts();
        
    }
PreparedStatement pst;
   
    Connection con1;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtCostDisplay = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanage/statistics_100px.png"))); // NOI18N
        jLabel2.setText("STATISTICS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 361, 97));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Most expensive Medicine:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Least expensive Medicine:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Most bought:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Least bought");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Expired Medicines:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total medicines sold:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total sales:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        jButton1.setText("<---");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 70, -1));

        txtCostDisplay.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCostDisplay.setText("jLabel10");
        jPanel2.add(txtCostDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        label2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label2.setText("jLabel10");
        jPanel2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        label3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label3.setText("jLabel11");
        jPanel2.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        label4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label4.setText("jLabel12");
        jPanel2.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        label5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label5.setText("jLabel13");
        jPanel2.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        label6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label6.setText("jLabel14");
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, -1, -1));

        label7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label7.setText("jLabel15");
        jPanel2.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanage/icons8-hospital-96.png"))); // NOI18N
        jLabel1.setText("ROFFE PHARMA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
public void maxCost(){
 try {
              int c;
              
              // TODO add your handling code here:
              Class.forName("com.mysql.jdbc.Driver");
              con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");
                      pst = con1.prepareStatement("SELECT * FROM stocks ORDER BY stkmdcn_cost DESC LIMIT 0,1");
                      
                        ResultSet rs = pst.executeQuery();
                        if(rs.next()){
                         txtCostDisplay.setText(rs.getString("stkmdcn_name"));
                             }
             
                
         
            
      
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
          }

}   

public void minCost(){
 try {
              int c;
              
              // TODO add your handling code here:
              Class.forName("com.mysql.jdbc.Driver");
              con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");
                      pst = con1.prepareStatement(" SELECT MIN(mdcn_cost), mdcn_name FROM `customer`");
                      
                        ResultSet rs = pst.executeQuery();
                        if(rs.next()){
                         label2.setText(rs.getString("mdcn_name"));
                             }
             
                
         
            
      
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
          }

}   
public void maxbought(){
 try {
              int c;
              
              // TODO add your handling code here:
              Class.forName("com.mysql.jdbc.Driver");
              con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");
                      pst = con1.prepareStatement("SELECT mdcn_name, SUM(quantity)\n" +
"FROM customer\n" +
"GROUP BY mdcn_name\n" +
"ORDER BY SUM(quantity) DESC");
                      
                        ResultSet rs = pst.executeQuery();
                        if(rs.next()){
                         label3.setText(rs.getString("mdcn_name"));
                             }
             
                
         
            
      
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
          }

}   
public void minbought(){
 try {
              int c;
              
              // TODO add your handling code here:
              Class.forName("com.mysql.jdbc.Driver");
              con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");
                      pst = con1.prepareStatement(
"SELECT mdcn_name, SUM(quantity)\n" +
"FROM customer\n" +
"GROUP BY mdcn_name\n" +
"ORDER BY SUM(quantity) ASC");
                      
                        ResultSet rs = pst.executeQuery();
                        if(rs.next()){
                         label4.setText(rs.getString("mdcn_name"));
                             }
             
                
         
            
      
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
          }

}   
public void exp(){
 try {
              int c;
              
              // TODO add your handling code here:
              Class.forName("com.mysql.jdbc.Driver");
              con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");
                      pst = con1.prepareStatement("SELECT * FROM stocks\n" +
"WHERE stkexpiry_date < NOW()\n" +
"ORDER BY stkexpiry_date ASC \n" +
"LIMIT 0,30");
                      
                        ResultSet rs = pst.executeQuery();
                        if(rs.next()){
                         label5.setText(rs.getString("stkmdcn_name"));
                             }
             
                
         
            
      
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
          }

}   
public void tq(){
 try {
              int c;
              
              // TODO add your handling code here:
              Class.forName("com.mysql.jdbc.Driver");
              con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");
                      pst = con1.prepareStatement("SELECT SUM(quantity) FROM customer ");
                      
                        ResultSet rs = pst.executeQuery();
                        if(rs.next()){
                         label6.setText(rs.getString("SUM(quantity)"));
                             }
             
                
         
            
      
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
          }

}   
public void ts(){
 try {
              int c;
              
              // TODO add your handling code here:
              Class.forName("com.mysql.jdbc.Driver");
              con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");
                      pst = con1.prepareStatement("SELECT SUM(mdcn_cost) FROM customer ");
                      
                        ResultSet rs = pst.executeQuery();
                        if(rs.next()){
                         label7.setText(rs.getString("SUM(mdcn_cost)"));
                             }
             
                
         
            
      
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
          }

}   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel txtCostDisplay;
    // End of variables declaration//GEN-END:variables
}
